import { Movie, TVShow, SeasonDetails, MediaCredits } from '../../types/tmdb.types';

export const MOCK_MOVIES: Movie[] = [
  {
    id: 550,
    title: 'Fight Club',
    original_title: 'Fight Club',
    overview: 'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    backdrop_path: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    release_date: '1999-10-15',
    vote_average: 8.433,
    vote_count: 28490,
    popularity: 92.4,
    genre_ids: [18, 53],
    runtime: 139,
    tagline: 'Mischief. Mayhem. Soap.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 157336,
    title: 'Interstellar',
    original_title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdrop_path: '/xJHokMbljvjADYdit5fK5VQsXEG.jpg',
    release_date: '2014-11-05',
    vote_average: 8.444,
    vote_count: 35120,
    popularity: 145.8,
    genre_ids: [12, 18, 878],
    runtime: 169,
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.',
    poster_path: '/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdrop_path: '/xOMo8BRK7PfcJv9JCnx7s520Wio.jpg',
    release_date: '2024-02-27',
    vote_average: 8.168,
    vote_count: 5800,
    popularity: 180.2,
    genre_ids: [878, 12],
    runtime: 166,
    tagline: 'Long live the fighters.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer’s role in the development of the atomic bomb during World War II, exploring the moral and political dilemmas that shaped his legacy.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    release_date: '2023-07-19',
    vote_average: 8.1,
    vote_count: 9200,
    popularity: 110.5,
    genre_ids: [18, 36],
    runtime: 180,
    tagline: 'The world forever changes.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 27205,
    title: 'Inception',
    original_title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: '/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    release_date: '2010-07-15',
    vote_average: 8.367,
    vote_count: 36200,
    popularity: 115.3,
    genre_ids: [28, 878, 12],
    runtime: 148,
    tagline: 'Your mind is the scene of the crime.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 155,
    title: 'The Dark Knight',
    original_title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg',
    release_date: '2008-07-16',
    vote_average: 8.516,
    vote_count: 32000,
    popularity: 130.0,
    genre_ids: [18, 28, 80, 53],
    runtime: 152,
    tagline: 'Welcome to a world without rules.',
    status: 'Released',
    media_type: 'movie',
  },
  {
    id: 299536,
    title: 'Avengers: Infinity War',
    original_title: 'Avengers: Infinity War',
    overview: 'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A despot of intergalactic infamy, his goal is to collect all six Infinity Stones, artifacts of unimaginable power, and use them to inflict his twisted will on all of reality.',
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    backdrop_path: '/mDfJG3LC3Dqb67AZ52x3Z0jOS0n.jpg',
    release_date: '2018-04-25',
    vote_average: 8.246,
    vote_count: 29000,
    popularity: 160.4,
    genre_ids: [12, 28, 878],
    runtime: 149,
    tagline: 'An entire universe. Once and for all.',
    status: 'Released',
    media_type: 'movie',
  }
];

export const MOCK_TV_SHOWS: TVShow[] = [
  {
    id: 1399,
    name: 'Game of Thrones',
    original_name: 'Game of Thrones',
    overview: 'Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night\'s Watch, is all that stands between the realms of men and icy horrors beyond.',
    poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    backdrop_path: '/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg',
    first_air_date: '2011-04-17',
    vote_average: 8.45,
    vote_count: 23500,
    popularity: 210.6,
    genre_ids: [10765, 18, 10759],
    number_of_seasons: 8,
    number_of_episodes: 73,
    tagline: 'Winter Is Coming',
    status: 'Ended',
    media_type: 'tv',
  },
  {
    id: 1396,
    name: 'Breaking Bad',
    original_name: 'Breaking Bad',
    overview: 'Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years to live. He chooses to enter a dangerous world of drugs and crime to secure his family\'s financial future.',
    poster_path: '/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg',
    backdrop_path: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    first_air_date: '2008-01-20',
    vote_average: 8.91,
    vote_count: 14200,
    popularity: 195.0,
    genre_ids: [18, 80],
    number_of_seasons: 5,
    number_of_episodes: 62,
    tagline: 'All Hail the King',
    status: 'Ended',
    media_type: 'tv',
  },
  {
    id: 66732,
    name: 'Stranger Things',
    original_name: 'Stranger Things',
    overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    poster_path: '/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    first_air_date: '2016-07-15',
    vote_average: 8.61,
    vote_count: 17100,
    popularity: 188.4,
    genre_ids: [10765, 18, 9648],
    number_of_seasons: 4,
    number_of_episodes: 34,
    tagline: 'Every ending has a beginning.',
    status: 'Returning Series',
    media_type: 'tv',
  },
  {
    id: 94605,
    name: 'Arcane',
    original_name: 'Arcane',
    overview: 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.',
    poster_path: '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
    backdrop_path: '/2RM43Z9og24VsY5pX2egv2ypbxO.jpg',
    first_air_date: '2021-11-06',
    vote_average: 8.74,
    vote_count: 4200,
    popularity: 140.8,
    genre_ids: [16, 10765, 10759, 18],
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: 'Witness the genesis of legend.',
    status: 'Returning Series',
    media_type: 'tv',
  }
];

export const MOCK_SEASON_DETAILS: Record<string, SeasonDetails> = {
  '1399-1': {
    id: 3624,
    season_number: 1,
    name: 'Season 1',
    overview: 'Trouble is brewing in the Seven Kingdoms of Westeros. For the driven inhabitants of this visionary world, control of Westeros\' Iron Throne holds the lure of great power.',
    poster_path: '/wgf2PmrLIZY2maC2bpEgv5pum6u.jpg',
    air_date: '2011-04-17',
    episodes: [
      {
        id: 63056,
        episode_number: 1,
        season_number: 1,
        name: 'Winter Is Coming',
        overview: 'Jon Arryn, the Hand of the King, is dead. King Robert Baratheon plans to ask his oldest friend, Eddard Stark, to take Jon\'s place.',
        still_path: '/9hGFvJqZc3bLqWpP8y6YjUj9d2k.jpg',
        air_date: '2011-04-17',
        vote_average: 8.4,
        runtime: 62
      },
      {
        id: 63057,
        episode_number: 2,
        season_number: 1,
        name: 'The Kingsroad',
        overview: 'Having accepted the role of Hand of the King, Ned leaves his home at Winterfell with his daughters Arya and Sansa, while Catelyn stays behind to tend to Bran.',
        still_path: '/wrGWeW4WKxnaeA8ZIO2qWjh1pWB.jpg',
        air_date: '2011-04-24',
        vote_average: 8.6,
        runtime: 56
      },
      {
        id: 63058,
        episode_number: 3,
        season_number: 1,
        name: 'Lord Snow',
        overview: 'Ned Stark arrives at King\'s Landing and is shocked to learn of the Crown\'s profligacy from his new advisor, Littlefinger.',
        still_path: '/7m3N0L0b1G3e4D5G6H7I8J9K0L1.jpg',
        air_date: '2011-05-01',
        vote_average: 8.3,
        runtime: 58
      }
    ]
  },
  '1396-1': {
    id: 3572,
    season_number: 1,
    name: 'Season 1',
    overview: 'High school chemistry teacher Walter White\'s life is turned upside down when he discovers he has terminal lung cancer.',
    poster_path: '/1BP4xYv9ZG4ZVHkL7ocOEZBbSYH.jpg',
    air_date: '2008-01-20',
    episodes: [
      {
        id: 62085,
        episode_number: 1,
        season_number: 1,
        name: 'Pilot',
        overview: 'When an unassuming high school chemistry teacher discovers he has lung cancer, he decides to secure his family\'s financial future by producing high-grade methamphetamine.',
        still_path: '/aG2s7rIeL5N6O7P8Q9R0S1T2U3.jpg',
        air_date: '2008-01-20',
        vote_average: 8.9,
        runtime: 58
      },
      {
        id: 62086,
        episode_number: 2,
        season_number: 1,
        name: 'Cat\'s in the Bag...',
        overview: 'Walt and Jesse attempt to clean up the messy aftermath of their first drug deal, with disastrous and grimly humorous results.',
        still_path: '/bG2s7rIeL5N6O7P8Q9R0S1T2U4.jpg',
        air_date: '2008-01-27',
        vote_average: 8.4,
        runtime: 48
      }
    ]
  }
};

export const MOCK_CREDITS: Record<number, MediaCredits> = {
  550: {
    id: 550,
    cast: [
      { id: 287, name: 'Brad Pitt', character: 'Tyler Durden', profile_path: '/cckcYc2v0yh1tc9QjRelptsqpH1.jpg', order: 0 },
      { id: 819, name: 'Edward Norton', character: 'The Narrator', profile_path: '/5XBzD5WuTyVQZeS4VI25LnqvOnB.jpg', order: 1 },
      { id: 1283, name: 'Helena Bonham Carter', character: 'Marla Singer', profile_path: '/mW1NolxQmPE16Zg6zu8iCOpqvgX.jpg', order: 2 }
    ]
  },
  157336: {
    id: 157336,
    cast: [
      { id: 10297, name: 'Matthew McConaughey', character: 'Joseph Cooper', profile_path: '/e9AHHGqolXmU9Qn07d0fT2W1r9q.jpg', order: 0 },
      { id: 1813, name: 'Anne Hathaway', character: 'Dr. Amelia Brand', profile_path: '/tLpq59r9c836tBwPj3v2x5P5h3p.jpg', order: 1 },
      { id: 1892, name: 'Jessica Chastain', character: 'Murphy Cooper', profile_path: '/lOz1bOvd1N80J2E8z8rXb5G7Y6Y.jpg', order: 2 }
    ]
  }
};
